// 汉字 → 拼音首字母。给快捷入口用：打 "qywx" 能搜到「企业微信」，打 "wyyyy" 能搜到「网易云音乐」。
//
// 为什么自带一张表而不是装依赖：整个主进程零运行时依赖，为一个首字母表引一个几 MB 的
// 拼音库不划算。表覆盖 CJK 基本区 U+4E00–U+9FA5（20902 字），够所有常见应用名与常用语名。
// 用 Python 的 pypinyin 离线生成，逐字取读音首字母。
//
// **多音字**是这件事唯一的难点，而且躲不掉：逐字取音必然出错——「音乐」的乐单字最常见读音是
// lè，于是「网易云音乐」会得到 wyyyl，可用户想打的是 wyyyy；「重庆」同理会得到 zq 而不是 cq。
// 词组级消歧要一张十万条的词典，不值当。这里的做法是**给多音字保留一个备选读音，按名字展开出
// 若干条候选串**，任意一条被命中就算命中。实测常见应用名平均只展开出 2.2 条，代价可以忽略。
// 展开数封顶 MAX_VARIANTS，超了就对后面的字只取主读音（宁可少一条候选，不能让长名字炸开）。
//
// 只做首字母，不做全拼：打 "qiye" 搜不到「企业微信」，打 "qy" 可以。
const START = 0x4e00;
const END = 0x9fa5;
// 一个名字最多展开多少条候选串。8 条足够覆盖三个多音字，再多是噪音也是浪费。
const MAX_VARIANTS = 8;

// 主读音表：下标 = 码位 - START，值 = 首字母，"." = 没有读音（10 个）。每 100 字一行只为可读。
const PRIMARY = [
  "ydkqsxhwzssxjbymgcczqpssqbycdscdqldylybsgjgyqzjjfgcclzzbwdwzjljpfyynwjjtmyyzwzhflyppqhgccyyymjqyxxgj",
  "xhsdsjnjjsmhmlzrxyfsngsyczqzggllyjlmyzssecykyyhqwjssggyxyqyjtwkdjhychmyxjtlxjyqbyxdldwrrjjwysrldzjpc",
  "bzjjbrcfslbczstzfxxthtrqggbdlyccscymmrfcyqzpwwjjyfcrwfdfzqpyddwyxkyjawjffxjpdftzyhhycyswccyqsclcxxwz",
  "zxnbgnnxbxlzsqcbsgpysyzdhmdzbqbzcwdzzyytzhbtsyyfzgntnxqywqskbphhlxgybfmjebjhhgqtjcysxstkzglyckglysmz",
  "xyalmeldccxgzyrcxsdltjzcqkcnnjwhjczzcqljststbnxbtyxceqxgkwjyflzqlyhjqspsfxlfpbyqxxxydcczylllsjxfhjxp",
  "jbcffyabyxbhczbjyclwlczggbtssmdtjcxpthyqtgjjscjfzkjzjqnlzwlslhdzbwjncjzyzsqnycqyrzcjjwybrtwpyftwexcs",
  "kdzctbxhyzcyyjxzcfbzzmjyxxcdczottbzljwfcgszsxfyrlnyjmbdthjxsqjccsbxyytsyfbjdztgbcnclcyzzbsacyzzscjcs",
  "hzqydxlbpjllmqxtydzxsqjtzpxlcglqccwjbhctdjjsfxjejjtlbgxsxjmyjjqpfzasyjncydjxkjcdjszcbartcclnjqmwnqnc",
  "lllkbybzzsyhqcltwlccrshllzntylnewyzyxczxxgdkdmtcedejtsyys.dqdfmsd.jlhrwnqlybglxhlgtgxbqjdzfyjsjyjcjm",
  "rnymgrcjczgjmzmgxmmryxkjnymsgmzjymklfxmbdtgfbhcjhkylpfmdxlqjjsmtqgzsjlqdldgjycalcmzcsdjllnxdjffffjcz",
  "fmzffpfkhkgdpqxktacjdhhzdddrrcfqyjkqccwjdxhwjlyllzgcfcqdsmlzpbjjplsbcjggdckkdezsqsckjgcgkdjtjllzycxk",
  "lqscgjcltfpcqczgwbjdqsdjjbyjhsjddwgfsjgdkccctllpspkjgqjhzzljplgjgjjthjjyjzcjmlzlyqbgjwmljkxzdznjqsyz",
  "mljlljkywxmkjlhskjgbmclyymkxjqlbmclkmdxxkwyxwslmlpsjqjcqxyjfjtjdxmxxllcrqbsyjbgwywxggbcyxpjtgpepfgdj",
  "gbhbnsfjyzjkjkhxqfgqzkfhygkhdgllsdjjxpqykybnqsxqnszswhbsxwhxwbzzxdmndjbsbkbbzklylxgwxjjwaqzmywsjqlcj",
  "xxjqwjeqxscwetlzhlyyysdzpyqyzcptlshtzcfycyxyljsdcjjagyslcllyyysglrqqeldxzsccccadycjysfsgbfrsszqsbxjp",
  "sjwsdrckgjlgdkzjzbdktcsyqpyhstcldjlhmxmcgxyzhjdctmhltxzxylymohyjcltyfbqqjbfbdfehtksqhzywwcnxxcdwhhwg",
  "yjlegmdqcwgfjhcsntwydolbygwqwesjpwnmlrydzsztxyqpzgcwxhngpyxshmdqjgztdppbfyhzhhjyfdzwkgkzbldntsxhqeeg",
  "zxylzmmzyjzgszxkhkhtxexxgylyapsthxdwhzydpxagkydxbhnhxkdfjnmyhylpmgocslnzhkxxlbzzlbmlsfbhhgsgyyggbhsc",
  "yajtxwlxtzqcwzydqdqmmgdqllszhlsjzwfjhqswscelqazynytlsxthaznkzzsdhlacxtwwcsgqqtddyzbcchyqzflxpslzygpz",
  "sznglydqcbdlxjtctajdkywnsyzljhhdzcwnyyzyomhychhhxhjkzwsxhdnxlyscqydpclyzwmypbkxyjlkzhtyhaxqsyshxasmc",
  "hkdscrswjpwqsgzjlwwschs.hsqnhzsngndaqtbaalzzmsstdqjcjktscjaxplggxhhgoxzcxpdmmhldgtybysjmxhmrcplxjzck",
  "zxshflqxccdhxezfchzccdytcjyxqhlxdhypjqxnlsyydzozjnyxqezysjyayjkypdghddxsppyzndlthrhxydpcjjhtcxmctlhb",
  "ynyhmhzllhnxmylllmdcppxhmxdkycyrdltxjchhznxclcclylnzsxzjzzlnnllwhyqsnjhxynttdkyjpychhyegkcttwlgqrlgg",
  "tgtygyhpyhylqyqgcwyqkpyyyttttlhyhlltyttsplkyzwgywgpydqqzzdqxskcqnmjjzzbxyqmjrtfbbtkhzkbjdjjkdjjtlbwf",
  "zpbtkqtztgpdgntpjyfalqmkgxbcclzfhzclllladpmxdjhlcclgyhdzfgyddgcyyfgydxkssebdhykdkdkhnaxxybfbyyhxcqga",
  "bfqyjjdmljcsjzllpchbsxgjyndybyqspqwjlzkcddtaccbkzdyzypjzqsjnkktknjdjgyepgtlfyqkasdntcyhblgdzhbbydmjr",
  "ygkzyheyybcmcdtyfzjjhgcjplxhldwxjjkytcyksssmtwcttqzlzbszdtwzxgzagyktywxlhlcpbclloqmmzsslcmbjcszzkydc",
  "zxgqjdsmcytzqqlwzqzxssbpkdfqmddzdsddtdmfhtdyzjaqjqkypbdjyyxtljhdrqxxxhaydhrjlklytwhllrllrcxylbwsrszz",
  "symkzzhhkyhxksmzsyzgcjfbzbsqlfcxxxnxkxwymsddyqwggqmmyhcdzttfgyyhgstttybykjdhkyjbelhdypjqnfxfdqkzhqkz",
  "byjtzbxhfdxbdaswhawajldyjsfhbldnndnqjtjnchxfjsrfwhzfmdrfjyhwzpdjkzyjymfcyznynxfbytfwfwygdbnzzzdnytxz",
  "emmqbsqehxfzmbmflzzsrsymjgsxwzjsprydjsjgxhjjgljjynzjjxhgjkymlpeyycsysgqzswhwlyrjlpxslcxmfsmwkcctnxny",
  "npnjszhdzeptxmwywayysywlxjqzqxzdclaeelmcpjpclwbxsqhfwrtffjtnqjhjqdxhwlbyccfjlalkyyjldxhhycstdywncjtx",
  "ywdrmdrqhwqcmfjdyzmhmayxjwmyzqsxtlmrspwwchajbxtgcypxyyrrclmpamgkqjszyjrmyjsnxtplnbappypylxmyzkynldgy",
  "jzczhnlmzhhanqmpgwqtzmxxmllhgdzxyhxkrxycjmffxyhjfsbssqlhxndycannmtcjcyprrnytyqnyymbmsxndlylysljnlqys",
  "hqmllyzlzjjjkymzcsfbzxxmstbjgnxyzhlsnmcqscyznfzlxbrnnnylmnrtgzqysatswryhyjzmzdhzgzdwybsscskxsyhytsxg",
  "cqgxzzbhyxjscrhmkkbsczjyjymkqhzjfnbhmqhysnjnzybknqmcjgqhwlsnzswxkhljhyybqcbfcdsxdldspfzfskjjzwzxsddx",
  "jseeegjscssmgclxxkywyllymwwwgydkzjgggtggsycknjwnjpcxbjjtqtjwdsspjxzxnzxwmelptfsxtllxcljxjjljsxctnswx",
  "lehhlyqrwhsycsqrybyaywjejqfwqcqqcjqgxaldbzzyjgkgxpltqyfxjltpadkyqhpmatlcpdhkxmtxybhblefxdleegqdymsaw",
  "hzmljtwyqxlyjzljeeyxbqqffnlyxrdsctgjgxyylkllxqkcctlhjlqmkkzgcyygllljdzgydhzwxpysjbzkdzgyzzhywyfqytyz",
  "szyezklymhjjhtsmqwyzlkyywzcsrkqyqltdxwcdrjklwsqzwbdcqyncjsrszjlkcdcdtlzzzacqqczddxyplxcbqjylzllljddz",
  "jgyjyjzyxnyyynxjxkxdazwyrdljyyyrjlglldrxjcykywnqcclddnyyykyckczhjxcclgzqjgjwppcqqjysbzzxyjxjbxjfzbsb",
  "dsfnsfpzxhdwztdmpptblzzbzdmyypqjrsdzsqzsqxbdgcpzswdwcsqzgmdhzxmwwfybpdgphtmjthzsmmbgzmbzjcfzhfcbbzmq",
  "cfmbcmcjxlgpnjbbxgyhyyjgptzgzmqbqdcgybjxlwzkydpdymgcftpfxyztzxdzxtgkmtybbclbjaskytssqyymscxfjeglslls",
  "zbqjjjaklyldlycctsxmcwfgkkbqxlllljyxtyltyxytdpjhnhgnkbyqnfjyyzbyyessessgdyhfhwtcjbsdzjtfdmxhcnjzymqw",
  "srxjdzjqpdqbbsdjggfbkjbxdgjhmgwjjjgdllthzhhyyyyyysxwtyyyccbdbpypzyccztjpzywcbdlfwzcwjdxxhyhlhwczxjtc",
  "zlcdpxdjczczlyxjjsjbhfxwpywxzptdzzbdccjhjhmlxbqxxbylrddgjrrctttgqsczwmxfytmwzcwjwxjywcskybzqccttqnhx",
  "nkxxkhkfhtswoccjybcmpzzyjbnnzpbthhjdlscddytyfjpxyngfxbyqxcbhxcbsxtyzdmzysnxsxlhkmzxlthdhkghxjsshqyhh",
  "cjyxglhzxcsnhekdtgqxqypkdhextykcnymyyypkqyytjxzlthhqtbyqhxbmyhsqckwwyllhcyylnneqxqwmcfbdccmljggxdqkt",
  "lxkgnqcdgzjwyjjlyhhqtttnwchhxcxwheszjydjccdbqcdgdnyxzdhcqrxcbmztqcbxwgqwyybxhmbymykdyecmqkyaqyngyzsl",
  "fykkqgyssqyshjgjcnxkzycxsbkyxhyylstycxqthysmgscpmmgcccccmtztasmgqzjhklosqylswtmqsyqkdzljqqyplcycztcq",
  "qpbbqjzclpkhqcyyxxdtdddsjcxffllchqxmjlwcjcxtspycxndtjshjwxdqqjckxyamylsjhmlalykxcyydmamdqmlmcznnyybz",
  "kkyflmchcmlhxrcjjhsylnmtjggzgywjxsrxcwjgjqhqzdqjdzjjzkjkgdzqgjjyjylhzxxcdqhhhestmhlfsbdjsyyshfyssczq",
  "lpbdrfrztzdkykgsctgkwdqzrkmsynbcrxqbjyfaxpzzedzcjykbcjwhyjbqdzywnyszptdkzpfpbaztklqyhbbzpnbptyzzybhn",
  "ydcpjmmcycqmcjfzzdcmnlfpbplngqjtbttajzpzbbdnjkljqylnbzqhksjznggqsczkyxchpzsnbcgzkddzqanzgjkdntlzldwj",
  "ljzlywtxndjzjhxyatncbgtzcsskmnjpjytsrwxcfjwjjtkhtzplbhsnjzsyjbwbzyzlstlsbjhdwwqpslmmfbjdwajyzccjtbnn",
  "rzwqxcdslqgdsdpdzhjtqqpsqlyyjzlgyhszlctcbjtktyczjtqkbpjlgmjzdmcsgpynjzjjyyknhrpwszxmtncszzyxybyhyzax",
  "ywkcjtllckjjtjhgcxdxyqyczbywblwqcglzgjgqrqcczssbcrbcskydznljsqgxssjmecnstztpbdlthzwhqwqtzexnqczgwesk",
  "ssbybstscsjccgbfsdqszlccglllzghzcthcnmjgyzaznmckcstjmmzckbjygqljyjppldxrgzyxccsnhshgdznlzhzjjcddcbcj",
  "flbfqbczzwpqdnhxljcthqwjgylnlszzpcjdscqqhjqkdxkpbajyemsmjtzdxlcjyryynwjbngzzkmjxltbsllrtpylcsznxjhll",
  "hyllqqzqlxymrcwcxsljmczltzldwdjjllnzggqxppskygyggbfzpdkmwghcxmcgdxjmcjsdycabxjdlnbcddygskydjtxdjjyxm",
  "saqazdzfslqxyjsjzylblxxwxqqzbjzlfbblylwdsljhxjyzjwtdjcyfqzqzzdcsxzzqlzcdzfchyspympqzmlpplffxjjnzzyls",
  "jyyqzfpfzksywjjjhrdjzzxtxxglghtdxcskyswmmtcwybazbjkshfhgcxmhfqhyxxyzftsjyzbxyxpzlchmzmbxhzzssyfdmncw",
  "dabazlxktcshhxkxjjzjsthygxsxyyhhhjwxkzxcsbzzwwhhcwtzzzpjxsnxqqjgzyzawllcwxzfxgyxyhxmkyyswsqmnjnaycys",
  "pmjkgwcqhylajjmzxhmmcnzhbhxclxtjpltxyjhdyylttxfszhyxxsjbjyayrsmxyplckdlyhlxrlnllstyzyyqygyhhsccsmcct",
  "zcxhyqfpyyrpfflfqtntszllzmhwtcjqyzwtllmlmdwmbzssmzrbpdddlgjjbxccsrzqqygwcsxfwzlxccrbtdzmcyggdlqsgtjm",
  "wljmymmsyhfbjdgyxccpshxczcsbsjwjgjmpbwaffyfnxhydxzylremzgzcyhsszdlljcsqfzxxkptxzgxjjgbmyyysnbdylbnlh",
  "bfzdcyfbmgqrrmsszxysgtznnydzzcdgbjafjbdknzblcsscpsgzycjszlmlrzzbzzldlsllysxsqzqlyxzlsgkbrxbrbzcycxzj",
  "zeeyfgklzlyyhgysgzlfjhgtgwkraajyzkzqtsshjjxdzyz.yjlzyrzdqqhgjzxsszbtkjpbfrtjxllfqwjgslqtymblpzdxtzag",
  "bdhzzrbgjhwnjtjxlhscfsmwlldqysjtxkzscfwjlbxftzlljzllqblcqmqqcgcdfpbbhzczjlpyygjdtgwdcfczqyyyqysrclqz",
  "fklzzzgffsqnwglhjycjjczlqzcyjbjzzbpdccmhjgxdqdgdlzqmfgpsytsdyfwwdjzjysxyycjcyhzwpbyhxrylybhkjksfxtzj",
  "mmchhlltnyymsxxyzpyjjycdyzwmtjjkqyrhllqxpsgtlwycljscbxjyzfnmlrgjjtyzbsyzmsjyjhgfzqmsyxrszcwtlrtqzsst",
  "kxgqggsptgcdnjsgcqcqhmxggztqydjkzdlbzsxjlhyqgggthqscpyhjhhgnygkggcmjdzllcclxqsftgzslllmlcskctbljzzsz",
  "mmnytpzsxqhjcjyqxyexzqzcpshkzzysxcdfgmwqrllqxrfztlysdctmjcsjjdhjnxtnrztzfqrhqgllgcxszsjdjljcytsjtlny",
  "xhszxcgjzyqpylfhdjsbpcczgjjjqzjqdybssllcmyttmqtbhjqnnygkynqyqmzgcjkpdcgmyzhqllsllclmholzgdylfzsljcqz",
  "lylzcjeshnylljxgjxlyjyyyxnbcljsswcqqcjyllcldjyllzllbnylgqchxyyqoxccqkyjxxhyklksxayqccqkkkkcsgyxxyqxy",
  "gwtjohthxpxxcsshcyeychzzcbwqbbwjqcscszsslzylgdesjzmmymcytsdsxxscjpqqsqylyfzychdjdzywcbtjsydjhcyddjlb",
  "djjsodzyqysqkxxdhhgqjyohdyxwgmmmajdybbbppbcmhcpljzsmtxerxjmhqdstpjdcbssmsssthjtslmmtrcplzszmlqdsdmjm",
  "qpnqdxcfynbfsdqqyxhyaykqyddlqyyysszbydslntfgtzqbzmchdhczcwfdxtmqqsphqwwxsrgjcwtjtzzqmgwjjrjhtqjbbgwz",
  "fxjhnqfxxqywyyhyscdydhhqmnmdmmcpbszppzzglmzfollcfwhmmsjzttthlmyffytzzgzyskjjxqyjzqphmbzzlyghgfmshpcf",
  "zsnclpbqsnjszslxjfpmtyjygbxlldlxpzjypjyhhzcywhjylsjexfsszywxkzjlladtmlymqjpwxxhxsktqjezrpxxzghmhwqpw",
  "qlyjjqjjzszcfhjlchhnxjlqwzjhbmzyxbdhhypylhlhlgfwlcfyytlhjjcjmscpxstkpnhjxsntyxxtestjctlsslstdlllwwyh",
  "dhrjzsfgxssyczykwhtdhwjslhtzdqdjzxxqggyltzphcsqfzlnjtclzpfstpdynylgmjllycqhynsbchylhqyqtmzybbywrfqyk",
  "jsyslzdyjmpxyyssrhzjnyqtqdfzbwwdwwrxcwhgyhxmkmyyyhmsmzhngcepmlqqmtcwctmhmxjpjjhfxyyzsjzhtybmstsyjdtj",
  "jqytlhynbyqzlcxcnzwsmylkfjxlwgbypjytysylymzckttwlgsmzsylmpwlzwxwqzssaqsyxyrhssntsrapccpwcmgdhhxzdzxf",
  "jhgzttsbjhgyglzysmyclllybtyxhbbzjkssdmalhhycfygmqypjycqxjllljgclzgqlycjcctotyxmtmshllwcgfxymzmklpszz",
  "zxhhjyslctyjcyhxsgyxzkxlzwpyjpdhjwpjpwsqqxlxxdhmrslzcyzwstcxkystzshbsccstplwsscjchjlcgchssphylhfhhxj",
  "sxyllnylmzdhzxylsxlwzyhcldyahzcmddyspjtqjzlngjfsjshctsdszlblmssmnyymjqbjhrcwtyydchqljapzwbgqybkfcmjw",
  "lzllyylszydwhxpsbcmljpscgbhxlqhyrljxyswxhxzlldfhlslymjljyflyjycdrjlfsyzfsllcqyqfgjyhyszlylmstdjcyhbz",
  "llnwlxxygyyhbmgdhxxhhlzzjzxczzzcyqzfnjwpylcpkpykpmclgkdgxzggwqbdxzzkzfbxxlzxjtpjpttbytszzdwslchzhslt",
  "jxhqlhyxxxywzyswtmzkhlxzxzpyhgchkjfsyh.tjrlxfjxptztwhplyxfcrhxshxkjxxyhzjdxjwylhyhmjdbflkhtxcwhcfwjc",
  "fpqrxqxcyyyjygrpxgscsxngwchkzdxhflxxhjjbyzwtsxnncyjjymswzjqrmhxzwfqsylzjzgbhynslbgttcsebhxxwxyhhxyxn",
  "sqyxmlywrgyqlxbbcljsylpsytjzyhyzawlhorjmksczjxxxyxchcytryxqjddsjfslyltsffyxlmtyjmjjyyyxltzcsxqzlhzxl",
  "wyxzhdnlrxhxjcdyhlbrlmbrllaxksllljlyxxlycrylcjcgjcmtlzllcyzzpzpcyawhjjfybdyyzsepckzdqyqpbpcjpdcyzbdb",
  "bcyydycnnpjmtmlrmfmmgwygbsjgygsmdqqqztxmkqwgxllpjgzbqcdjjjfpkjkcxbljmswmdtqjxldlppbxcwkcqqbfqjczagzg",
  "mykbhyyhzykndkzmbpjyspxthlfpnyygxjdbkxnhhjhzjxstrstldxskzysybmxjlxyslbzyslhxjpfxbqnbylljqkygzmcyzzym",
  "ccsldlhzgwfwyxzmwcxtynxjhbyymcysbmhysmydyshqyzchmjjmzcaahcbjbbhplxtylsxsdjgjdhkxxtxxnbhnmlngsltxmrhn",
  "lxqjxmzllyswqgdlbjhdcgjyqycmhwfwjybbbyjmjwjmdpwhxqldyapdfxxbcgjspckrssyzjmslbzzjfljjjlgxzgyxyxlszqyx",
  "bexyxhgcxbpldyhwecdwwcjmbtxchxyqxllxflyxlljlssfwdpzsmyjclmswtczbchqekcqbwlcgydblqppqzqfjqdjhymmcxtxd",
  "rmjwrhxcjzclqxdyynhyyhrslsrsywwzjymtltllgzqcjzyabsckzcjyccqljsqxalmzyyywlwdxzxqdllqshgpjfjljhjabcqzd",
  "jgthhsstcyjlbswzlxzxrwgldlzrlzqtgsllllzlymxqgdzhgbdbhzpbrlw.xqbpfdwo..whlypcbjcc.dmbzpbzz.cyqxldomzb",
  "lzwpdwyygdstthcsqsccrsssyslfybfntyjszdfndpthtzzmbblxlcmyffgtjjqwftmdpjwdnlbzcmmctgbdzlqlpyfhsymjylsd",
  "chdzjwjcctljcldtljjcpddpjdsszynndbjlggjzxsxnlycybjjqxcbylzcfzppgkcxzdzfztjjfjsjxzbnzyjqttyjwhtyczhym",
  "djxttmpxsflzcdwslshxybzgtfmlcjtacbbmgdewycyzcdszcyhflyctygwhkjyylsjcxgywjcbhlcsnddbtzbsclyzczzssqdll",
  "mqyyhfllqllxfdyhabxggnywyypllsdldllbjcyxjzmlhljdxyyqytdlllbbgbfdfbbqjzzmdpjhgclgmjjpgaehhbwcqxaxhhhz",
  "chxyphjaxhlphjpgpzjqcqzgjjzzgzdmqyybzzphyhybwhazyjhykfgdpfqsdlzmljxjpgalxzdaglmdgxmwzqytxdxxpfdmmssy",
  "mpfmdmmkxksyzyshdzkjsysmmzzzmsydnzzczxbmlstmddnmxckjmztyymzmzzmsshhdccjemxxkljstgwlsqlyjzllsjssdbpmh",
  "nlyjczyhmxxhgzcjmdhxtkgrmxfwmckmwkdcksxqmmmfzzydkmsclcmpcgmwrpxqpzdsslcxkyxtmlgjyahzjgzqmcsnxyhmmpml",
  "kjxmhlmlgmxctkzmjjyszjsyszhsyjzjcdajzybsdqjzgwzkgxfkdmsdjlfmehkzqkjbeypzyszcdwyjffmzjykttdzzefmzlbnp",
  "plplpbpszalltylkckqzkgenqlwagxxydpxlhsxqqwqykxqclhyxxmlyccwlymqyskychlcjnszkpyzkcqzqljbdmdjhlasqlbyd",
  "wqlwdnbqcrydddtjybkbwszdxdtnpjdtctqdfxqqmgnseclstbhpwslctxxlpwydzklzygzcqapllkccylbqmqczqcljslqzdjxl",
  "dthpzqdljjxzqdjyzhkzljcyqdyjppypeakjyrmpcbymcxkllzllfqpylllmbsglcysslrsysqtmxyxqqzbdzrysyztffmzzsmzq",
  "hzssccmlyxwtpzgxzjgzgsjsgkddhtqggzllbjdzlcbzhyxyzhzfywxyzymsdbzzyjgtsmtfxqyxjscdgslnmdlrytzlryylxqht",
  "xsrtzcgyxbnqqzfhykmzjbzymkbpnlyzpblmcnqyzzzsjzhjctzhhyzzjrdyzhnfxglfxslkgjtctssyllgzrzbbjzzklpkbczys",
  "lxyxbjfpnjzzxcdwxzyjxzzdjjgggrsrjkmcmzjlsjywqshyhqjsxpjzzzlsnshrnypjtwchklbsrzlcxwjqxqkysjycztlqzybb",
  "ybwzjqdwgyzcytjcjxckcwdkkzxsgkdzxwwyyjqyytcytdjlxwkczkklcclzcqqdzlqlcsfqchqhsfsmqzzllbjjzbsjhtsjdysj",
  "qjpdlzcdcwjkjzzlpycgmzwdjjbsjqzsyzyhhxcbbjydssddzncglqmbtsfcbfdzdlznfgfjgfsmptjqlmblgqcyyxbqkdxjqsrf",
  "kztjdhczklbsdzcfytplljgjhtxzcsszzxstcygkgckgyoqxjplzbbbgtgyjdgczqszlbjlsjfzgkqqjcgyczbzqtldxrjxbsxxp",
  "zxhyzyclwdsjjhxmfczpfzhqhqmqgkslyhtycgfrzgnqxclpdlbzcsczqlljblhbdcypczppdymtzsgyhckcpzjgslclnscdsldz",
  "xbmsdlddfjmkdjdhslzxlszqpqpgjllybdszgqlbzlslkyyhzttncjyqtzzfszqztlljtyyllqllqyzqlbdzlslyyzymdfszsnhl",
  "xznczqzbbwskrfbcyzmthblgjpmczzcstlxshtzcyzlzblfeqhlxflcjlyljqcbzlzjghsstbrmhxzhjzclxfnbgxgtqjcztmsfz",
  "kjmssnxljkbhszxntnlzdntlmsjxgzjyjczxyhyhwrwwqnztnfjscpzshzjfyrdjsfscjzbjfzqzchzlxfxsbzqlzsgyftzdcszx",
  "zjbqmszkjrhxjzcgbjkhchgtjkjqglxbxfgdrtylxjxgdtsjxhjzjjcmzlcqsbtxhqgxttxhxftsdkfjhzyjfjxrzcdlllcqsqqz",
  "qwqxswqtwgwbzcgcllqzbclmqqtzgzxzxljfrmyzflxysqxxjkxrmjdcdmmyxbsqbhgcmwfwtgmxlzbyytgzyccdxyzxswgxyjyz",
  "nbgpzjcqsyxcxrtfycgrhztxszzthcbfclsyxzljqmzlmplmxzjssflbysmyqhxjsxrxsqzzzsslyflczjrcrxhhzxqydshxsjjh",
  "zcxjbdynsysxjbqlpxzqpymlxzkyxlxcjlcycrxzzlldlllsjyhzxgyjwkjrwyhcpsgnrzlfzwfzznsxgxflzsxzzzbfcsyjdbrj",
  "krdhhgxjljjtgxjxxstjtjxlyxqfcsgswmsbctlqzzwlzzkxjmltmjyhsddbxgzhdlbmyjfrzfcgclyjbpmlysmsxlszjqqhjzfx",
  "gfqfqbpxzgyyqxgztcqwyltlgwwgwhllfsfgzjmgmgbgtjfsyzzgzyzaflsspmlbflcwbjzcljjmzlpjjlymqdmyyyfbgygqzgly",
  "zdxqyxrqqqhsxyyqqygjtyxfsfsllgnqcygycwfhcccfxbylypllzqxxxxxkqhhxshjdcfdsczjxcpzwhhhhhapylhalpqafyhxd",
  "yllkmzqgggddesrnndltzgchybpysqjjhclljtolnjpzljlhymheydydsqycddhgzpndzclzywllznteytgxlhslpjjbdgwxpcdn",
  "tjcklkclwkllcasstknzdnqnttlyyzssysszzryljqkcgbhhcrxrzydgrgcwcgzhfffppjfzynakrgywyqpqxxfkjtszzxswzddf",
  "bbqtbgtzfznpzfpzxzpjszbmqhkcyxyldkljnypkyghgdcjxxeahpnzgctzcmxcxmmjxnkszqnmnlwbwwxjjyhclstmcsqdjcxxt",
  "pcnpdtnnpglllzcjlspblplkcdtnjnlyyrscffjfqwdpgzdwmnzcclodaxnssnyzrestyjwjyjdbcfxnmwttbqlwstszgybljpxg",
  "lboclgpcbjftmxzljylzxcltpnclcgxtfzjshcrxsfyszdkntlbyjcyjllstgqcbxnwzxbxklylhzlqzlnzcqwgzlgzjncjgcmnz",
  "zgjdzxtzjxycyycxxjyyxjjxsssjstssttppghtcsxwzdcsyfptfbchfbblzjclzzdbxgcxlqpxkfzflsyltywbmnjhskbmddbcy",
  "sccldxycddqlyjjhmqllcsgljjsyfpyyccyltjantjjpwycmmgqyysqdhqmzhszxpftwwzqswqrfkjlxjqqyfbrxjhhfwjgzyqac",
  "myfrhcyybyqwlpexcczstyrltsdmqlykmbbgmyyjprknnbbsxyxbhyzdjdnghpmfsgbwfzmfjmmbcmzzcjjlcnyxyqgmlrygqccy",
  "hzlwjgcjcggmcjjfyzzjhycfrrcmtzqzxhfqgdjxccjeaqcrjthpljlszdjrbcqhjdzrhxlyxjsymhzydwldfryhbbydtssccwbx",
  "glpzmlzztqsscpjmmxjcsjytycghycjwsnsxlfemwjnmkllswtxhyyygcmmcwjdqdjzglljwjnkhpzggflccsczmcbltbhbqjxqd",
  "jpdjqtghglfqawbzyjjltstdhqhctcbchflqmpwdshyytqwcnztjtlbypbpdyyyxsqkxwyyflxxncwcxybmaelykkjmzzzbrxyaq",
  "jfljpfhhhytzzxrgqqmhspgdzjwbwpjhzjdyscqwzkthxsqlzyymysdzgrxckkhjlwpysyscsyzlrmlqsyljxbcxtlhdqzpcycyk",
  "pppnsxfyzjjrcemhszmsxlxglrwgcstlrsxbygbzgztcpldjlslylymdtmtcpalcxpqjcjwtcyyzlblxbzlqmyljbghdslssdmxm",
  "bdczsxwhamlczcpjmcnhjyjnsygchskqmzzqdllkablwjqsfmocdxjrrlyqchjmybyqlrhetfjzfrfksryxfjdwdsxxlwsqjysly",
  "xwjhsnlxyyxhbhawhhjcxwmyljcsqlkydttxbzsxfdxgxsjhhsxxybssxdpwncmrptjzczenygcxqfjxkjbdmljcmqqxloxslyxx",
  "lylljdzbtymhbfsttqqwlhogyblscalzxqlhtwrrqhlstmypyxjjxmqsjpnbryxyjllyqylthylqyfmhkljdmllhfzwkzhljmlhl",
  "jkljstlqxylmbhhlnlsxqchxcfxxlhyhjjgbyzzkbxscqdjqdsxjzsyhzhhmgsxcsymxfebcqwwrbpyyjqtyqcyjhqqzyhmwffhg",
  "zfrjfcdbxndqyzpcyhhjlfrzgppxzdbbgzqstlgdgylcqmgchhmfywlzyxkjlypqhsywmqqgqzmlzjnsqxjqsyjtcbehsxfssfxz",
  "wfllbcyyjdytdthwzsfjmqqyjlmqsxlldttkhhybfpwdyysqqrnqwlgwdebdwcyygcdlkjxtmxmyjsxhybrwfymwfrxyqmxysctz",
  "ztfykmldhqdlwyqnlcryjblpsxcxywlsbrrjwxhqybhtydnhhgmmywytzcsqmtssccdalwztcpqpyjllqzyjswxwzzmmglmxclmx",
  "czmxmzsqtzppjqblpgxjzhfljjhycjsnxwcxsccdlxsyjdcqcxslqyclzxlzzxmxqrjmhrhzjphmfljlmlclqnldxzlllfypngjy",
  "sxcqqdcmqjzzxhnpnxzmekmxxykyqlxsxtxjxyhwdcwdzhqyybgybcyscfgfsjnzdyzzjzxrzrqjjymcanhrjtldbpyzbstjhxxz",
  "ypbdwfgzzrpymtngxzqbyxmbbfcckrjjjbjegrzgyclkxzdxkknsjkcljspgyyzlqqjybzssqlllkjfcbktylcccdblsppfylgyd",
  "tzjyqggkqttfcxbdkdxxhybbfytyhbclpdytgdhryrnjsbtcsnyjqhklllzslydxxwbcjqsbxbfjzjcjdzfbxxbrmlazgcsnclbj",
  "dstblfrzdswsbxbcllxxlzdjzsjpylyxxyftfffbhjjjgbygjpmmmmsscljmtlyzjxswxtyledqpjmygqzjgdjlqjwjqllsdgjgy",
  "gmscljjxdtygjqjqjcjzcjgdzdshqgsjggcjhqxsnjlzzbxhsgzxcxyljxyxyydfqqjhjfxdhctxjyrxysqtjxyefyyssyxjxncy",
  "zxfxcsyszxyyschshxzzzgzzzgfjdldylnpzgyjyzyyqzpbxqbdztzczyxxyhhscxshcggqhjhgxwsztmzmehyxgebtylzkkwytj",
  "zrclekestdbcykqqsayxcjxwwgsbhjszsdhcsjkqcxswxfctynydpzcczjqtzwjqdzzzqzljchlsbhpydxpsxshhezdxfptjqyzz",
  "xhyaxncfzyyhxgnqmywxtzsjpkhhgymxmxqcxtsbcqsjyxhtyylybcqlmmszmjzjllcogxzaajzyhjmchhcxzsxzdznleyjjzjbh",
  "zwzzsqtzpsxztdsxjjjznyazphhyysrnqdthzhayjyjhdzxzlswclybzyecwcycrylcxnhzydzydyjdfrjjhtrsqtxyxjrjhojyn",
  "xelxsfsfjzghpzsxzszdzcqzbyyklsgsjhczshdgqgxyzgxchxzjwyqwgyhksseqzzndzfkwyssdclzstsymcdhjxxyweyxczayd",
  "mpxmdsxybsqmjmzjmtzqlpjyqzcgqhxjhhhxxhlhdldjqsldwbsxfzzyyschtytyjbhecxhjkgjfxbhyzjfxbwhbdzfyzbcapnpg",
  "nydmsxhkhhmamlnbyjtmpxyjmcthjbzyfcgtyhwphftgzzezsbzegpbmdskftycmhbllhgpzjxzjgzjyxzsbbqsczzlzccstpgxm",
  "jsftcczjzdjxcybzlfcjsyzfgszlybcwzzbyzdzypswyjgxzbdsysxlgzbzfygczxbzhzftpbgzgejbstgkdmfhyzzjhzllzzgjq",
  "zlsfdjsscbzgpdlfzfzszyzyzsygcxsntxchczxtzzljfzgqsqyxzjqccccdjcdxzjyqjccgxztdlgscxzsyjjqtcclqdqztqchq",
  "qjztezzzpbkkdjfcjfztybqyqttynlmbdktjcpqzjdzfpjsbnjlgyjdxjdzqkzgqkxclpzjtcjdqbxdjjjstcjnxbxcmslyjcqmt",
  "jqwwcjjnjnlllhjcwqtbzqyczczpzzdzyddcyzdzccjgtjfzdprntctjdcqtqndtjnplzbcllctdsxkjzqdpzlbznbtjdcxfczdb",
  "ccjjltqjpldcgzdbbzjcqdcjwynllzlzccdwllxwzlxrsntqjccxkjlsgdfqtddglrlajjtklymkqlldzytdyycygjwyxdxfrsks",
  "tcdenqmrkqzhhqkdldazfkypbggpzrebzzykyzspegjjglkqzzzslysywyzwfqznlzzlzhwcgkypqgnpgblplrrjyxcccgyhsfzf",
  "wbzywtgzxyljczwhxzjzblfflgskhyjzeyjhlpllllcygxdrzelrhgklzzyhzlyqszzjzqljzflnbhgwlczcfjwspyxnlzlxgccp",
  "zbllcxbbbbxbbcbbcrnncccyrbbsyldcgqyyqxygmqzwtzydyjhyfwdehzdjywlccntzyjjcdedpzdztstqjhdymbjnyjzlxtsst",
  "phndjxxbyxqtzqddtjtdyztgwscszqflshlglbcjbhdlyzjyckwtydylbnydsdsycctyszyyebgexhqddwnygyclxtdcystqmygz",
  "asccszzddlcclzrqxyyeljsbymxshztembbllyyllytdqyshymrqxkfkbfxnxsbychxbwjyhtqbpbsbwdzylkgzskyghqzjhhxjx",
  "gnljkzlyycdxlfwfghljgjybxblybxqpqgztzplncybxdjyqydymrbesjyyhkxxstmxrczzywxyhybmcflyzhqyzmqxdbxbzwzms",
  "lpdmyckfmzklzcyjycclhxfzlydqzpzygyjyzmzxdzfyfyttqtchgspczmlccytzxjcytjmkslpzhysnwllytpzctzzcktxdhxxt",
  "qcypksmqccyyazhtjpcylzlyjbjxtfnyljyynrxcylmmnxjsmybcsysslzylljjgyldzdpqbfzzblfndsqkczfhhhgqmrdsxycst",
  "xnqqjpyjbfcxdyqfbnxejdgyqbsrcnfyyqpghyjdyzxgrhtkyleqdzntsmgklbsgbpyszbytjzsszjcssxzbhbscsbzczptqfzmq",
  "flypybbjgszmxxdjmthyskkbjtxhjcegbsmjyjzcxtmljyxrzzqscxxqptzxmkyxxxjcljprmyygadyskqlsadhrskqxzxztcghz",
  "tlmlwxybwsycdbhjhcfcwzsxhytkzlxqshlyczjxemplprcgltbzztlzjcyjgdtclglpllqpjmzpapxyzlaktkdnczzbnzctdqqz",
  "jyjgmctxltgcszlmlhbglkfwnwzhdxphlfmkydlgxdtwzfrjejctzhydxykshwfzcqshktmqqhtchymjdjskhxzjzbzzxympajqm",
  "sdbxlsklyynwrtsqlscbpdbsgzwyhtlkssswhzzlyytnxjgmjszsxfwnlsoztxgxlsammlbwldszylakqcqctmycfjbslxclzjcl",
  "xxksbzqclhjphqplsxsckslnhpsfqqytxjjzlqldxzjjzdyydjnzptfcdskjfsljhylzqjzlbthydgdjfdbyazxdzhzjnhhqbykn",
  "xjjqczmlljzkspldsclbblxklelxjlbjycxjxgcnlcqplzlznjtzljgyzdzpltqcssfdmnycxgbtjdcznbgbqyqjwgkfhtnbyqzq",
  "gbkpbbyzmtjdytblsqmbsxtbnpdxklemyycjynzdtldykzzxddxhqshdgmzsjycctayrzlpwltlkxslzcggexclfxlkjrtlqjaqz",
  "ncmbqdkkcxglczjzxjhptdjjmzqykqsecqzdshhadmlzfmmzbgntjnnlgbyjbrbtmlbyjdzxlcjlpldlpcqdhlhzlycblcxzcjad",
  "qlmzmmsshmybhbskkbhrsxxjmxsdznzpxlbbragggfchgmsklltsjyycqlcskywyehywhbhqywbawykqldqftntkhqcgdqktgpkx",
  "hcpdhtwtmssyhbwcrwxhjmkmzngwtmlkfghkjyldyycxwhyeclqhkqhtdqhhffldxqwgzyydesbpkyrzpjfyyzjceqdzzdlattbb",
  "fjllcxdlmjsdxegygsjqxcfbxsszpdyzcxdnyxpfzydlyjccpltxlsxyzyrxcyysdylwwndsahjsygyhgywkaxtjzdaxysrltdjs",
  "saxfnejdxyzhlxlllzhzsjnyqyqqxyjghzgjcyjchzlycdshwsgczyjxcllnxzjjyyxnfsmwfpylcyllabwddhwdxjmcxztzpmlq",
  "zhsfhzynztlldywlslxhymmylmbwwkyxyadtxylldjpybpwfxjmmmllhafdllaflbhhhbqqjtzjcqjjdjtffkmmmbythygdcqrdd",
  "wrqjxnbysnmzdbyytbjhpybygtjxaahgqdqtmystqxkbtsbkjlxrbeqqhqmjjbdjwtgtbxpgbktlgqxjjjcdhxqdwjlwrfmqgwqh",
  "ckryswgbtgygbwsdwdwrfhwytjjxxxjyzyslphyypayxhydqkxshxyxeskqhywbdddpplcjlhqeewxksyyhdyplfjthkjltcyyhh",
  "jttpltzzcdlthqkcxqysteeywkyzyxxyysddjkllpwmcyhqgxyhcrmbxpllnqydqhxsxxwgdqbshyllpjjjthyjkyphthyyktyez",
  "yenmdshlcrpqfbgfxzbsbtlgxsjbswyysksflxlpplbbblbsfxfyzbsjssylpbbffffsscjdstzsxtryjcyffsytyzbjtbctsbsd",
  "hrtjjbytcxyjeylxcbnebjdsysyhgsjzbxbytfzwgenyhhthjhatfwgcstbgxklstywmtmbyxjskzscdyjrcytwxzfhmymcxlzns",
  "djtttxrycfyjsbsdyerxhljxbbdeynjghxgckgscymblxjmsznskgxfbnbbthfjaafxyxfpxmyfhdtzcxzzpxrsywzdlybbjtyqw",
  "qjpzypzjznjpzjlztfysbttslmptzrtdxqsjehbzylzdhljsqmlhtxtjecxalzzspktlzkqqyfsygywpcpqfhqhytqxzkrsgtgsq",
  "czlptxcdyyzssqzslxlzmacbcqbzyxhbsxlzdltcdjtylzjyytpzylltxjsjxhlbmytxcqrblzssfjzztnjydxmyjhlhpblcyxqj",
  "qqkzzscpzkswalqsblcczjsxgwwwygyatjbbctdkhqhkgtgpbkqyslbxbbckbmllxdzstbklggqkqlsbkkdfxrmdkbftpzfrtbbm",
  "ferqgxkjpzsstlbzdpszqzsjthljqlzbpmsmmsxlqqnhknblrddnhxdhddjcyygyfqgzlgsygmjqgkhbpmxyxlytqwlwgcpbmjxc",
  "yzydrjbhtdjxeeshtmjsbyplwhlzffnypmhxqhpltbqpfbcwjdbygpnxtbfzjgsddtjshxeawzzyllttybwjkgxghlfkxdjtmszs",
  "qynzggswqsphtlsskmclzxyszqzxncjdqgzdlfnykljcjllzlmzznhydsshthxzlzzbbhqzwwycrdhlyqqjbeyfsgxthsrxwqhwf",
  "slmssgzttyeyqqwrslalhmjtqjsmxqbjjzjxzyzkxbyqxbjxshzssfglxmxzxfghkzszggylclsarjxhslllmzxelglxydjytlfb",
  "hbpnlyzfbbhptgjkwetzhkjjxzxxglljlstgshjjyqlqzfkcgnndjsszfdbctwwseqfhqjbsaqtgypjlbxbmmywxgslzhglzgnyf",
  "ljbyfdjfrgsfmbyzhqfbwjsyfyjjphzbyyzffwodgrlmftmlbzgycqxcdjygzyyyytytydwegazyhxjlzythlrmgrjxzclhneljj",
  "thtbwjybjjbxjjtjteekhwsljplpsfazpqqbdlqjjtyyqlyzkdksqjyyjzldqcgjjyzjsycmraqthtejmfctyhypkmhycwjdcfhy",
  "yxwshctxrljgjshccyyyjltkttytmxgtcjtzayyoczlylbszywjytsjyhbyshfjlygjxxtmzyyltxxypclxyjzyzyypnhmymdyyl",
  "blhlsyygqllnjjymsoycbzgdlyxylcqyxtszegxhzglhwbljgeyxtwqmakbpqcgyshhegqcmwyywljyjhyyzlljjylhzyhmgsljl",
  "jxcjjyclycjpcpzjzjmmylcjlnqljjjlxxjmlszljqlycmmhcfmmfpqqmfxlqmcffqmmmmhmznfhhjgtthhkhslnchhyqdxtmmqd",
  "cydyxyqmyqylddcyyydazdcymzydlzfffmmycqcwzzmabtbyctdmndzggdftypcgqyttssffwbdtzqssystwjjhjytsxxylbyqhw",
  "whxezxwznnqzjzjjqjccchyyxbzxccyjtllcqxknjycyycynzzqyyoewyczdcjycchyjlbtzkycqwlpgpyllgkdldlgkgqbgychj",
  "xy"
].join("");

// 多音字的备选读音：「汉字 + 备选首字母」成对拼接。只留一个备选——留两个的收益远小于噪音。
const ALT_PAIRS = [
  "丁z丂q万m丌q不f且j丞s丱k串g丼d丿y乁j乂a乃a乇z么y乐y乑p乘s乙j乜n乾g乿l予z事z于w亏y亘x些s亝z亞e亟q亢g亥j亨x亶c亹m仅f仇q介g从z仛d仠h仡y以s仯m仰a仱j仳b件m",
  "仸f任l份b仿p伃x伈l伉g伋f伎z伒y众y会k传z伯m伴p伹z伺s伽j佁a佃t佄g但t佋s位l体b佔c佗y余t佚d佛b佝k佫g佮e佰m佴n佻d佼x侅h侉h侗t侟j侥y侧z侱t侲c侸d便p俆s俊s俏x",
  "俓y俔x俛m俞s俟s信s俥j俶s俸b俺y俾p俿c倀z倅z倍p倓d倕z倘c倚j倜d倞l倢q偅c假x偈q偒d偕j偞y偢q偪f偬c偲s側z偽e傀k傂s傋g傍p傔j傕q傛r傢x傪s傭c傮c傰p傳z傶q僁s僄b",
  "僋l僑j僔c僕b僜d僝z僣j僤c僥y僧c僪y僭z僮z價q儃s儋s儔d儗y儥d儭q儴x儵t儶x儻c儿r兄k免w兑r兒n兓z兔c兪s共h其j典t兹c内r冉n册z冯p冰n冼s净c凵k凹w划g刨b券x刹c刺q",
  "剅d削q前j剟c剠l剡y剢z剥p剬t副p剳z剴a創q剸z剹j剽b剿c劋c劗z劦l助c劾k勑l勖m務m勜y募b勥q勦j勭d勷x勺z勿m匀j包p匋y匕p匙c匡w匨c匮g匱k区o匼e匿t區o半p卑p卒c单c",
  "卙c卜p卝g卞p卟j占t卡q卤x卬y卵k卷q卹s卻j厂h厃y厈a厎z厓a厔s厕s厖m厘c厝j厦x厱q厶m厷h厸m厹q叀h参s參s叓l叕y受d叚x叟x古k句g叨t召s叭p可g台y叱h叶x号x司c叹y吁y",
  "吃q吅s吇j合g吋d吓h吖a吚x吟j吡p吤g吥p否p吧p吨t吩p吪h听y吭h吱q吲s吳y吴t吵m吷c吺r吽o吾y呀x呃a呅w呆b呇m呈k告j呎y呒m呔t呡m呫c呬c呮z呰c呲z味m呴h呵a呷x呹c呺h",
  "呼x呾y呿k咀z咁h咍t咎g咔n咖g咥d咦x咬j咭x咮r咯k咰x咳h咶s咸j咹a咼w哅h哆c哇g哈t哌g哏h哐q哕y哦e哧x哨x哩m哱p哺f哽y哾y唇z唊q唌y唑s唔n唝h唡y唪b唫y唬x唲w唵n唶j",
  "唸d唼q啁d啇s啈e啊e啋x啌q啍z啐z啑z啘w啙c啚t啜z啞e啡p啢y啨q啳j啴t啻d喈x喊k喋z喏r喔w喙z喛y喜c喝y喟h喠c喢c喥z喦y喫k喬j單c喯b喰s喳c喿q嗃x嗄s嗆c嗊g嗌y嗑h嗒t",
  "嗔t嗗g嗙b嗛x嗺s嘀z嘁z嘄d嘅g嘇c嘏j嘐j嘔x嘘s嘬z嘮c嘯c嘲z嘸w嘼x嘽t嘾t嘿m噁w噃b噆c噈z噋k噎s噡d噢y噣d噦h噫a噭q噱x噲g噴f噷x嚂h嚄w嚇h嚊x嚋z嚌z嚔z嚗p嚙y嚛y嚣a",
  "嚯x囁z囂a囃z囋c囐n囗g囝n团q囤t园w圈j團c圜y土d圣k圩x圪y圫t圱s圳q圻y坆f均y坈k坉d坋f坏p坓x坔l块y坢p坥j坨y坫z坬w坯h坳y坷j坻d垂z垌t垠k垦y垧j垩s垸h垺p垾a埃z",
  "埄f埅d埆j埉x埏y埐q埔b埝d埡e埢j埤b埥z埩c埫t埯y埱t埳x埶s埻d埿b堆z堇q堊y堋b堕h堝w堡p堤t堥w堧n堨e堪c報f堲j場s堵z堷p堿k塂j塈x塌d塔d塗d塜p填c塲s塹j塼t墅y墆d",
  "墐q增c墠c墢f墤t墥t墫c墮h墲w墽a墿t壅w壆j壇s壏l声q壳q夃y夆p夏j夕y夗w夘w大t夬j夭w夯b失y夲b夵t夹g夾x奃t奇j奊l奋k奏c契x奓s奔f奟k奠t奡x奤p奥y奲c女r奵t奸g她j",
  "妁y妃p妋y妎j妔h妖j妗x妚p妜j妞h妧y妯c妷y姍x姐x姓s姕c姚t姣x姥m姫z姬y姰x姱h姶y姺x姼t姽w娃g娊d娍s娒w娕l娝b娞s娩w娪y娭x娶j娷s娾e婄b婑w婕q婘j婜j婠g婤z婥n婩n",
  "婫h婸y婺m婼r媂t媆n媐x媕y媞t媠d媪y媮y媰z媲b媵s媿c嫀s嫅s嫈x嫎b嫖b嫗k嫚y嫢z嫥t嫧c嫨n嫶j嬈y嬐y嬗c嬛x嬥d嬬n嬭e孃r孅x孈x孉h孎s孖z孨n孫x孱j孴y學h宁z它y宅c宊j",
  "完k宓f宛y客q宲s家g容y宿x寘t寠l實z寨s審p寰x寵l封b尃b射y将q將q專t尉y尌z尚c尢w尥n尨p尵z尾y尿s屈j屎x屏b属z屟t屬z屯z屰p屵y屸h屹g屽a岂k岈x岋j岎c岨j峇k峊n峒t",
  "峙s峤q峫y峿w崎y崒c崛y崤y崥b崫j崵d崼d嵁z嵇x嵊c嵌h嵍m嵑j嵒n嵣t嵤y嵦a嵪k嵺j嶄c嶉z嶒z嶜q嶠q嶡j嶦s嶮y嶰j嶷n嶼x巂x巆h巋w巙n巛s巜h巠x巡y巨q差j己q已s巳y巷h巽z",
  "巿p币y市f帑n帓w帕m帗f帘c帱d帴j帹q帺j幅b幆k幓q幘c幠w幢z幬d干a平b幵q幸n幹h幺m幾q广y庄p庇p庉t庍x度z庳p庵y庶z廁z廆w廈x廑q廞q廣k廧s弁p弄l弆q弇n式t弟t弡z弮j",
  "弲y強j弹t强j彀k彈t彊q彌n彖s彗s彡x彦p彭b彯m彳f彴b彵y彷f徎z徙s從z徥t徦x徧p徬b徲c徵c徸z徼y忀r忂j忊t忏q忐k忑d忓h忔y忕t忚l忞w忪z忬s忮q忯s忱d忳z忹w忼h忾q怀f",
  "怐k怕b怗z怘g怙t怚q怞y怠y怢d怫b怵x怶p恁r恂s恃z恆g恌y恍g恑w恓q恔x恗k恝q恫t恮z恶w恿t悁j悂b悆s悇y悈k悎j悛x悝l惆q惊l惌w惐x惓j惔d惛m惝t惡w惢r惰t惴c惵t惽h惿s",
  "愁q愉t愍f愒q愓s愖d愘k感h愠w愩h愾x慅c慉c慊x慎z慝n慥c慬j慳x慴z慸c憁s憕z憖x憚c憞t憢j憧z憾d懁h懆s懊y懝n懠j懢x懽g戆z戇g戌q戏h戔c戕z或y戚c戛g戡z戧c戯x戲h戺y",
  "房p扁p扄j才z扐c扒p扚y扛g扜w扝w扞h扠z扡y扢q扭c扮f扰y扱c扳p扶p扸z扺q扻s找h承z技q抂w抄s把p抌s抐r投d抗g折s抝n抨b抪p抬c抭t抱p抲q抴s抵z抻s押x拁y拂b担j拈d拊b",
  "拌p拍b拓z拔f拖c拗n拘g拚b招q括g拱j拴q拵z拸c拺s拼b拽y拾j挃d挄g挈j挌h挐r挑d挕s挝z挟j挫z挻y挼s挾j捁k捄q捆h捇c捈s捊f捍x捎x捐y捔z捖g捗p捝s捥y捧f捬b捰l捲q捵t",
  "捶d捷q捼w捽c捾x掀h掇z掉n掊f掎y排b掔w掘k掜n掝x掞y掟d探x接x控q措z掫c掱s掸s掺s掾c揁k揂y揃q揄c揈x揊c揌c揍c提d插z揔s揖j揘h揞y揟j握o揢q揣d揥d揩j揭q揰d揱s揲s",
  "揳j援h揵j搉h搊z搋y搑n搒p搕e搚x搛l搜x搞q搤y搥d搨d搩j搫b搬s搭t搰k搱n搳x搶c搷s摌s摎l摓p摕t摖c摡x摢c摧z摨z摪q摮q摰c摳o摵m摶z摷c摺l摻s摼q摽p撅g撇b撋s撍q撓x",
  "撕x撖q撜c撝w撟k撢t撣c撥f撨x撫m撮z撰x撱t撲b撽y撾z撿l擇y擊x擏j擐j擔s擖q擗b擣c擩n擭h擳j擴t擽y擿z攃s攄l攈p攉q攒c攕j攘n攙s攝z攢c攤n攦s攩t支q攲j攼h敃f敄m敊s",
  "敌h敕s敞z敠q敥j敦t敧q敫q敱z敺o斁d斄t斗z斜c斡g斥z斦z斫c斮z斳j方p斺j於w施y斿l旁b旄w旇b族s无m既x旬j旮x旰h旲y旽z昂y昆h昋j昔c昙y昞f昧w是t昰x昳y昵z晁z晇k晟s",
  "景y晵d晻y暅x暇j暏d暕l暖x暠h暧n暴p曏s曝b曷e曾z最c朁q會k月r有w朊w朌b服b朏k朐x朓y朘j朚m朝z朞q期j朣c札y朮z术z朱s朷m朹q机w朾z杂d杅w杒e杓s杔z杜t杝z杣s杫z杭k",
  "杮b杴q杷b杸d杻n杼s枂y枇b枈p枉k枋b析s枓z枕c枘n果l枝q枞z枮z枯g枱s枸j枹f枻x柁t柂d柅c柈p柑q柙j柚z柜j柟r柠c柢c柣d查z柨p柭f柮z柴z柵z柷z柸b柹f柽j栅s栎y栒s栓q",
  "栖x栜c栝t校j栩y栫z核g栺z格l桃z桅g桊q桋t桐d桔x桙m桧h桭c桯y桲b桿h梀y梋j梌c梎y梏j梘x梡k梢x梣q梧y梩s梭x梱h棁t棇s棋j棍h棏z棑b棓p棣t棧c棬j棯s棰d棱c棲x棴s棷s",
  "棽c椄q椆z椉s椊c椌k椎z椏e椑p椯c椲h椷h椹z椾z楂c楇g楖j楛k楤c楥y楪d楬q楮z楯s楱c楴d楷j概j榅y榐c榑b榜p榝x榦h槀k槁k槇z構j槌z槍c槏x槛j槢d槣g槫s槭c槯z槱c槷x槽z",
  "槾w槿q樀z樁c樂y樅z樆c樔j樘c樚d樛l樞o樠l樢m樣x横g樲z樴y橈n橋j橏j橐d橔t橖c橙d橚x橝t橢d橦c橧c橪y橾q檀s檐d檘b檜k檞x檠j檡s檫s檮c檷m檻j檽r櫂d櫎g櫖c櫟y櫬q櫰g",
  "櫹q櫼s欀r欃z欈z權g欑z欓t次z欥h欦h欪x欬a欯k欱x欸x欹q欻x欽y款x欿q歁q歃x歇y歍y歏q歒x歖y歘x歙x歛l歭z歸k歹e歾w殁w殍b殑j殕y殖s殙m殨k殸k殺x殼q殽y毆k毋m母w比p",
  "毭n毳q毹y毼k氀s氂l氏z氐z氜r氣x氶c氼m氽q氿j汀d汁x汃p汋y汍h汏t汓y汖c汗g汙y池t汤s汥j汧y汩y汪h汭t汱f汵h汶m汸p決q汼y汽g汾p沆k沇w沈c沌z沓t沕w沗t沬h沮z沰d沱d",
  "沴z沶c治c沾t泂y泃g泄y泅y泆d泊b泌b泏k泑a泔h泖l泚z泜c泞z泣l泧x泫j泬x泵p泷s泺p洀z洊c洋x洒x洓q洚h洝y洞t洩y洫y洮y洯j洸h活g洼g洽h派m洿h浅j浍k浒x浚x浛g浟d浧c",
  "浩g浬h浲h浸q浹x浽n涀j涂c涇q涉d涊r涌c涎y涒y涓y涔q涡g涪p涭t液s涳n涴y淁j淈h淊h淌c淍d淑c淖z淙s淡y淢x淦h淨c淪g淬z淰s淲h淳z混g淺j渂m渑s渞w渠j渥o渦g渧t温y渫d",
  "港h渱g渴j游l渹q渾g湃b湍z湏m湔z湛c湝x湞c湟k湣h湩t湪n湫q湯s湴p湷h溃h溉x溎g溓x溚d溝k溥f溦m溪q溱z溴c溺r滀x滇t滈x滊q滋c滎y滑g滧x滯c滲q滸x漂b漎s漙z漡t漢t漦t",
  "漨p漬s漯t漴c漷k漸q漺c漻x潏j潐q潑b潒x潘b潙g潚x潝y潠s潢g潨z潬t潭x潯y潰x潳z潼c澄d澆a澉h澍z澠s澡c澤s澨c澫m澬c澮k澳y澴x澶d澹t濂x濄w濆p濈s濊w濎t濔n濕t濞p濟q",
  "濡e濢z濤c濫j濬x濭k濯s濺z濼p瀅j瀋c瀑b瀢d瀤w瀧s瀰n瀳z瀼n灂j灄n灌h灑x灒c灘h灥q灬h灹y炃b炅g炎t炏y炐f炔q炕h炖t炪c炮b炰f烄y烏y烔d烛c烜h烠a烲c烴j烻s焄h焆y焌q",
  "焏q焘t焞j無m焣j焥a焦q焬y焯z焸y焻g煇y煒h煔q煖x煠y煨y煴w煾y熀y熇x熑q熒x熙y熜z熝a熢b熣c熨w熯r燀d燂x燆x燉t燋q燌b燍x燖q燙d營c燠a燤l燥s燭k燹b燾t燿s爌h爍l爓x",
  "爞t爻x爾m爿q牑m牓p牞l牫q牰c牴z犄y犆t犍q犛l犧s犪r犴h犵h犺g犻p犿f狂j狄t狋q狌x狏y狟x狠y狡x狢m狤k狧s狪d狵z狶s狻x狼h猈p猎x猓l猗j猚w猭s猰j猲h猵p猼p獃a獋g獖f",
  "獝y獞z獟x獦x獪h獬h獮m獳r獶y獷j獻s獾q玀e玅y玆x率s王y玚y玟m玢f玧y玪y玵g珆t珇j珢k珵t珶t琁q琕b琗c琞w琟y琣p瑒y瑗h瑱t瑲c瑹t璅z璏z璚j璯k璷f璸p璾j瓊x瓕x瓗w瓛y",
  "瓟p瓠g瓡h瓨h瓩w瓿p甄j甎c甘h甫p甬d甭q甴y甸t町d甽q畇t畐b畗f畜x畟j畤c畨f番p畬y畸q畹y疋s疌q疐d疑n疔n疙y疟y疦x疨y疴e疵z疹c疺b痀g痋c痏y痑s痕g痡p痦p痪t痭p痳m",
  "痶d痷y痾k瘈z瘍d瘕x瘟y瘣l瘧y瘨c瘳l瘵j療s癉t癌y癐w癛b發b百m癿b皀x皅b皇w皋h皖h皛j皪b皻c皽d盅c盍k盒a盓w盛c監k盤x盩c盯c盳m盷x盹z盻p盼f盾s省x眃h眈c眑a眗x眙c",
  "眣c眩h眪f眫p眭h眰z眴s眼w睃j睄q睇t睉z睔h睖c睟z睢h睪z睫s睽j睾h瞀w瞉j瞋t瞏h瞠z瞤s瞥b瞯j瞴w瞶w瞷x瞿j矃c矆x矌g矔q矖l矜q矞j矣x石d矵d矸h矺d矻q矼k砉x砏f研x砝j",
  "砠z砢l砥z砲b砵e硄g硅h硊h硌l硍y硎k硐t硔g硜q硝q硞k硥b硧t硪e硫c硬g硾d碂c碈h碊z碏x碙g碟s碡z碣k碪a碮d碱x碿x磃t磅p磆k磈k磍q磎q磏q磑a磓z磚t磝q磩z磹d磺k磻b磼s",
  "磽a礆x礉q礊h礐h礘q礙y礦g示q祁z祇c祈g祊f祌c祕b祖j祝c祠s祢n祭z祱l禅s禓s禨q禪s禰n离c秅n秇z种c秏m秘b租j秤p积z秲s秳k秴g移c秿b稄z稌s税t稘q稞h稟l稠t稡s稧q稫b",
  "種c稴j稵j稷z稹b稽q稾k穇s穉c穋j穘r穛b穜t穧z穪b穮p穱j穳z穴j穵y穹k穿y窀t窋k窌p窐w窒d窖z窨y窬d窯q窶l窼k窾c立w竘k竜n童z竧z竵h竺d竻j笍r笏w笒j笓p笚x笤s笧s筊j",
  "筋q筍y筒d筠j筧x筩y筴j筽w箁b箄p箈c箉d箌z箎h箐j箑z箘q箠z箢w箬n箴j箵s箷s箹c箾x篅d篔x篢g篦p篧h篬c篲s篴z篸z篹s篻b篿z簉c簍j簎j簜t簨z簻k籈j籋m籌t籓b籧j籴z粃p",
  "粆c粇j粘n粢c粣s粥y粹s精q粿h糶d糸s系j約d紅g紆o紇g純z紕b紗m紡b紬z紲y紵s紹c紾t組q絏y絓k絔m絙g絜x絞x絠a絣p給j絧t絩d絮c絯h絹x絺z絻w綃s綄w綅x綆b綉x綏r綖x綝s",
  "綢t綪z維y綴c綷z綸g綺y緂c緄h総c緝q緟z緡h緤y緰x緶p緷g緼w縎h縐c縒s縗s縝z縱c縳z總c縿x繀c繁p繅z繆j繇z繑j繒c繘j繚r繩y繪g繫j繰s繳z繵t繹s繻r纀f纅l纔s纕x纖j纚x",
  "红g纤q纥h纶g给j缉q缏p缲s缴z缺k罜d罤k罫h罱n罷p羏x羗y羙m羛x羡y羧z義x羫k羬x羹l羽h翍b翛s翟z翢z翮l翵q耆z而n耎n耏e耑z耗m耙p耛c耝c耳r耶x耷z聉t聏n聑z聱y聶z職t",
  "聻j肄s肆t肋j肐q肑d肜c肢s肣q肥b肨f肩x肫c肮h育z肶b肷x肸b肺p胂c胆t胇b胍h胏f胔c胕z胜x胝c胞p胲g胵z胶x胺e能t胿k脀z脔j脘h脛k脞q脟p脠c脥j脦t脧z脨j脩y脪c脮t脯f",
  "脹c脺s脾b腂g腃q腄h腊x腌a腍d腏z腔k腝r腞d腧y腯d腱q膀p膁x膊p膔b膕h膘p膚l膞c膠h膪z膭k膰p膴w膸w膻d臈g臑r臒y臡l臤x臦j臧c臩j臭x臱b至d臷z臸j臾k舂z舄q舌g舒y舙q",
  "舡x舩f般p舼h舽f艌q艐j艞t艟z艧w艮h艴b艻j艼d艽q艾y艿r芋x芍x芎x芐x芒h芘b芚c芟w芥g芦h芧z芩y芪c芭p芴h芻z苐d苕t苙j苛h苞p苣q苦g苧z苩p苫t苴c苻p苼r苾m茀b茄q茇p",
  "茈z茋d茖l茛j茜x茝z茟w茠x茤d茧c茫h茭x茮n茲c茷p荃c荅t草z荑y荒k荖c荠q荤x荥y荨q荹p荼c荽w莀n莆f莉c莋j莑f莔x莖y莘x莜d莞w莠x莤y莥r莦x莧w莩p莬m菀y菅g菆c菍r菏g",
  "菥s菨s菩b菬z菭z華k菳j菴y菹z菽j萁j萆p萑z萒j萩j萭j萯b萷s萹p萿h葉s葐f著c葚s葝j葡b董z葥q葭x葰j葴q葶d葷x蒍h蒐h蒘n蒝h蒡p蒣s蒦w蒩j蒲b蒿g蓁q蓔z蓧t蓨x蓫z蓯z蓲o",
  "蓴t蓻j蓿s蔃j蔇x蔈p蔍c蔓w蔕c蔖z蔚y蔞j蔡s蔢b蔪s蔫y蔵c蔽p蕁t蕃b蕈t蕉q蕊j蕎j蕘y蕝z蕞j蕩t蕰y蕹y蕺q薁a薋z薍l薔s薙z薜p薟l薥z薧k薳y薵z薶w薺c藃h藇y藋z藏z藖q藥s",
  "藨p藪c藴w藷z藸z蘀z蘁e蘄j蘖b蘘x蘞x蘧j蘫l蘬h蘴s虑b虒x處j虠h虩s虫h虰c虵y虷g虹j虾h蚄b蚌p蚔z蚕t蚖w蚗q蚘y蚝c蚣z蚫p蚰z蚳d蚴n蚵k蚺t蚼q蚾b蛆j蛇y蛒l蛖b蛙j蛞s蛡x",
  "蛣j蛤g蛩g蛪n蛸x蛾y蜄z蜅p蜍y蜎x蜒d蜓d蜕y蜚p蜡q蜤x蜩d蜮g蜱m蜳t蜴x蜷j蜹w蜻j蜼t蜾l蝃z蝎h蝕l蝙p蝚n蝤y蝥w蝦h蝩z蝭c蝶t蝷x蝸l蝹a蝺y螃b螅c螇q螌p螔s螕p螛x螝h螫z",
  "螲d螶j螹c蟈y蟜q蟠f蟣q蟦b蟫x蟬t蟯r蟱m蟲z蟺d蟻j蟿j蠀j蠃g蠖y蠩c蠭p蠰s蠱y蠸h蠼j蠾s衃f行h衕d衖l衘y衯p衰c衹t衿q袂y袌p袍b袒z袔k袘t袚f袜m袢f袦j袩c被p袲n袳q袷q",
  "袸z袹m袼l裌x裒b裓j裢s裧t裨p裯d裳c裴f裷g裺a裼x裿q褆s褈z褊p褍t褎y褕t褘y褚z褞w褥n褨c褩p褶d褹n襃p襆p襈j襎b襏f襗d襘h襜d襝c襡d襢z襳s襸c覂b覃q見x規x覕p覘d覵b",
  "覿j见x角l觖k觝z觟x解x觭q觰d觳q觷h觿w訄k訇j訑d訜b訢y訤n訬m許h詀c詆t詑t詒d詘c詥g詧q詫d詬h詳y詶c詷d詹d詻l誀c誂d誃c誇q誒x説y誳j誺l調t諀b諎c諔j諕x諗n諜x諟d",
  "諣g諦t諫l諭t諰s諳t諴g諸c諿x謁a謅c謉d謍h謏s謓z謕s謙z謚y謜q謞x謣x謤p謯z謲z謳x謵c謶s謻c謼x譀x譁w譂d譊x譌w譑q譔q譕m譖j識z譧l譮x譸c譺y讉t许h识z说y调t谷l谾l",
  "谿j豃g豈k豉c豊f豚d豣y豧p豩h豫x豰h貀d貇m貈m貉m貍m貗y貫w貶f貸t費b賁f賈g賹a贇b贍d贛z贾g赦c赨x赫s赶q赺q赽g赿d趁z趃t趄q超t越h趍q趏h趐c趑c趙d趜q趞j趟z趠t趡w",
  "趣c趥c趨c趪g趫j趯y足j趵z趶w趹g趼y趽p趿s跁p跂j跅c跈j跌t跐z跑b跔q跕t跘b跙q跛p跢c跣s跤q跦c跧z跩s跬x跮d跰b跳d跼q跾c跿d踁k踃q踅c踆q踑j踒r踓c踔d踖q踜c踡j踢d",
  "踣p踤c踦q踧d踩k踰c踱c踶z踹s踻t踼s踾b蹃r蹄d蹅z蹊x蹍z蹔c蹚c蹛z蹢z蹣m蹨r蹱c蹲z蹴z蹶g蹻q躍t躒y躔z躠x躦z躩q身j軃t車j軋z軒h軙q軥g軧c軬b軵f軺d軼d軽q較x輅h輇c",
  "載d輐y輑q輗y輠h輦l輭e輱k輴s輵y輹b輼y輾n轁k轄h轇x车j轧z辗z辟b辥y辨p辯p辴z达t迆t迋g迒x还f迡c迣c迤t迦x迬w迭y迱y追d适k逄f透s逐d逗z逘s這y逛k逞y造c逡x逢p逫z",
  "逬p逯d逾d逿t遁q遃a遇o過h達t違h遗w遞s遟z適d遰s遲z選s遺w遽q還x邌c邑e邓s邚f邟h邢g邪y邺q郂h郃x郄x郅j郇x郍f郗c郚y郝s郢c部p郩a郰j郴l郵c鄒j鄗q鄜l鄤w鄫c鄵s鄹j",
  "鄿q酂z酄q酇c酈z酐h酖d酡d酢z酦f酮d酻f醀z醃a醈d醋z醎j醒c醔c醛c醧o醮q醱p醳s醶l醷a醻s釃l釋y重c野s釐x釓q釘l釤x釥j釪y釫w釬g釰j釶y釽z釿y鈀p鈂q鈆z鈈p鈉r鈊q鈐h",
  "鈒x鈕c鈗d鈚b鈲p鈶c鈷h鈾z鈿d鉀g鉃z鉄t鉆q鉇y鉈y鉋p鉍s鉏z鉐z鉗a鉚l鉛y鉤q鉥x鉨n鉩n鉮s鉵z鉺k鉻l鉼p鉿g銄j銉s銊h銐l銒j銕y銗h銚d銛t銴z銸n銹y銾g銿y鋀d鋅z鋆j鋋y",
  "鋌t鋑j鋖t鋗j鋘w鋙w鋜c鋞j鋟j鋤j鋨t鋭d鋷n鋺w錀f錁k錇f錋b錍b錎g錒k錕g錗z錞d錟x錡y錢j錣c錫t錭d錯x錽j鍇j鍉c鍊j鍖z鍩n鍱x鍺d鍼q鎈c鎉t鎊p鎐z鎑t鎒h鎗c鎘g鎚d鎝s",
  "鎞p鎣j鎬g鎮t鏂k鏃c鏒q鏓c鏕a鏖b鏩z鏸s鏾x鐀g鐍y鐖q鐟t鐰s鐱q鐲s鐵d鐶x鐺c鐻q鐼b鑐r鑛g鑠y鑯q鑲r鑴h钀y钭d钯p钿t铅y铛c铤t铫y铻y锬x镐h镡t長c长c閄s閈b開q閒j閘y",
  "閜e閞g閡h閧x閶t閼y闂x闆p闇y闋j闍s闕j闛c關w闞h闟s闣t阇s阏y阘t阚k阣y阤y阨a阬g阮y阸a阽y阿e陀d陁z陂p附b降x陏s限w陘j陚w陟d陠b除z陫p陰a陳z陴b陶y陼d陾e隃y隄t",
  "隊z隋d隑a隓d隔r隗w隘e隦p隧z隩y險j隶d隹c隺q隻h雃j雇h雉k雋z雚h雛j離c雩x雭x雱f雺m需n霅s震s霍s霧m霰s霸p霾l霿w靃s靉y青j靓l靘j靚l靦m革j靬j靸t靺w鞈s鞋w鞕b鞘s",
  "鞙j鞝z鞞p鞠q鞢z鞨s鞫q鞴f鞼h鞽j韃t韋h韏j韒s韛f韞w韡x韢h韹y頁x頃k頇a頌r頎k頏g頑k頒f頜q頞a頡j頦k頨b頫t頴j頸g頻b顃s顇z顈j題d顐h顑y顚t顡z顤q顩q顫z颈g颉x颌g",
  "颤z颩d颮p颯l颰f颳j颵x食y飦g飩z飬y飭s飱c飳z飴s飾c餄h餐s餙x餛k餡k餤d餧n餫h餰z餲h餳x饀x饋t饌x饐e饑q饧x饹g馇z馗q馘x馞p馥b馧w馮p馯q馱d馲t馶s馸j駃k駘d駱j騃s",
  "騆d騎j騤j騩t騫j騯b騶q騷x騺c驁y驃p驕x驡z驪c驫p驮d骀t骠p骯k骰g骱x骴z骸g骹j髂g髆p髈p髉j髟p髳r髶e髺y鬄t鬌c鬤n鬨x鬩h鬲l鬴l鬵x鬹x鬻z鬾q魄b魋c魟g魣y魤h魥q魭w",
  "魮b魳s魺g魼x鮆j鮈q鮋c鮍j鮏z鮑p鮚q鮝z鮥g鮧y鮨q鮭x鯆b鯈y鯖q鯦a鯨q鯽j鰈q鰓x鰔j鰖w鰜j鰟p鰥k鰨d鰪g鰺c鱃q鱄t鱓t鱖j鱣s鱦s鱮y鲑x鲭z鳥d鳩q鳭z鳱h鳷c鳺g鳻f鳽q鴁a",
  "鴂g鴓b鴖w鴝g鴢a鴩h鴳a鴹x鴺y鵁x鵃d鵅g鵍j鵏p鵠g鵣c鵪y鵬f鶄q鶉t鶌q鶗c鶝b鶣b鶨z鶩m鶬q鶻h鶼q鶽x鷉s鷕x鷸s鸀z鸂q鸊b鸛h鸟d鹄h鹘h鹹j麃b麆c麇q麕q麗s麙y麲y黐l黚j",
  "點z黨t黬j黮t黰y黱z黳w黵d黹x鼂z鼎z鼕t鼜c鼥f鼳x鼿h齁k齃h齊j齍j齐j齛s齜z齟z齦q齬w齮q齰c齱c齵y齾e龈y龍m龏w龐l龜q龟j"
].join("");

// 码位 → 备选首字母。模块加载时建一次表，查询期只做 Map.get。
const ALT = new Map<number, string>();
for (let i = 0; i + 1 < ALT_PAIRS.length; i += 2) {
  ALT.set(ALT_PAIRS.codePointAt(i) || 0, ALT_PAIRS[i + 1]);
}

// 这段文本里有没有表内汉字。没有就不用生成拼音别名（纯英文名不需要）。
export function hasHan(s: string): boolean {
  for (const ch of s) {
    const n = ch.codePointAt(0) || 0;
    if (n >= START && n <= END && PRIMARY[n - START] !== ".") return true;
  }
  return false;
}

// 逐字取主读音首字母，非汉字原样保留（转小写）。
// 「企业微信」→ "qywx"，「QQ音乐」→ "qqyl"，「Umbra 助手」→ "umbra zs"。
// 保留非汉字是为了让中英混排的名字整体仍可搜，而不是被切成两截。
export function pinyinInitials(s: string): string {
  let out = "";
  for (const ch of s) {
    const n = ch.codePointAt(0) || 0;
    const c = n >= START && n <= END ? PRIMARY[n - START] : "";
    out += c && c !== "." ? c : ch.toLowerCase();
  }
  return out;
}

// 展开成多条候选首字母串（第 0 条是全取主读音的那条）。
// 多音字各贡献一个备选，笛卡尔积展开；总数超过 MAX_VARIANTS 之后的字只取主读音。
export function pinyinVariants(s: string): string[] {
  const slots: string[][] = [];
  let n = 1;
  for (const ch of s) {
    const cp = ch.codePointAt(0) || 0;
    const prim = cp >= START && cp <= END ? PRIMARY[cp - START] : "";
    if (!prim || prim === ".") {
      slots.push([ch.toLowerCase()]);
      continue;
    }
    const a = ALT.get(cp);
    if (a && n * 2 <= MAX_VARIANTS) {
      slots.push([prim, a]);
      n *= 2;
    } else {
      slots.push([prim]);
    }
  }
  let out = [""];
  for (const opts of slots) {
    const next: string[] = [];
    for (const pre of out) for (const o of opts) next.push(pre + o);
    out = next;
  }
  return out;
}

// 给一组名字补上拼音别名：含汉字的名字各追加它的全部候选串，去重后返回。
// 追加而不是替换——原名要留着，否则中文本身就搜不到了。
export function withPinyin(names: (string | undefined | null)[]): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  const push = (v: string) => {
    const k = v.trim().toLowerCase();
    if (!k || seen.has(k)) return;
    seen.add(k);
    out.push(v);
  };
  for (const x of names) if (x) push(x);
  for (const x of names) if (x && hasHan(x)) for (const v of pinyinVariants(x)) push(v);
  return out;
}
